token = ""
clientId = ""
guildId = ""

[interactions.info]
logChannel = ""

[interactions.jp]
targetChannel = ""
translationTargetChannel = ""
deeplAPIKey = ""

[interactions.pendingrole]
role = ""

[interactions.swarm]
targetChannel = ""
