token = ""
clientId = ""
guildId = ""

[interactions.utility.info]
logChannel = ""

[interactions.utility.jp]
targetChannel = ""
translationTargetChannel = ""
deeplAPIKey = ""

[interactions.utility.pendingrole]
role = ""

[interactions.swarm]
targetChannel = ""
