token = ""
clientId = ""

[[servers]]
guildId = ""

[servers.attachments]
save = true
# Absolute path
outDir = ""
baseURL = ""

[servers.interactions.embedBan]
role = ""

[servers.interactions.info]
logChannel = ""
saveAttachments = false

[servers.interactions.jp]
targetChannel = ""
translationTargetChannel = ""
deeplAPIKey = ""

[servers.interactions.pendingRole]
role = ""

[servers.interactions.qol.autoMod]
sendFlagAttachments = true

[servers.interactions.qol.essaying]
emote = ""
threshold = 1000
ignoredChannels = []

[servers.interactions.qol.minecraftFix]
subRole = ""
minecraftRole = ""

[servers.interactions.qol.pollRestrictions]
enabled = false
globalMinutesPerChannel = 1
globalMinutesPerUser = 15
allowedRoles = []
disallowedChannels = []
bypassRoles = []
bypassChannels = []

[servers.interactions.qol.vedalReplyMention]
vedal = "170187485345742858"
logChannel = ""
ignoredRoles = []
ignoredChannels = []

[[servers.interactions.reactions.bans]]
enabled = false
name = "Sample Ban"
match = "samplename|sampleid"
channels = []
ignoredChannels = []

[servers.interactions.swarm]
targetChannel = ""

[servers.interactions.twitch]
authKey = ""
# vedal987: 85498365
pollUser = "85498365"
pollResultsChannel = ""
