token = ""
clientId = ""
guildId = ""

[attachments]
save = true
# Absolute path
outDir = ""
baseURL = ""

[interactions.embedban]
role = ""

[interactions.info]
logChannel = ""
saveAttachments = false

[interactions.jp]
targetChannel = ""
translationTargetChannel = ""
deeplAPIKey = ""

[interactions.pendingrole]
role = ""

[interactions.qol.automod]
sendFlagAttachments = true

[interactions.qol.essaying]
emote = ""
threshold = 1000

[interactions.qol.minecraftFix]
subRole = ""
minecraftRole = ""

[interactions.reactions]
notificationChannel = ""

[interactions.swarm]
targetChannel = ""

[interactions.twitch]
authKey = ""
# vedal987: 85498365
pollUser = "85498365"
pollResultsChannel = ""
