token = ""
clientId = ""
guildId = ""

[attachments]
save = true
# Absolute path
outDir = ""
baseURL = ""

[interactions.embedban]
role = ""

[interactions.info]
logChannel = ""
saveAttachments = false

[interactions.jp]
targetChannel = ""
translationTargetChannel = ""
deeplAPIKey = ""

[interactions.pendingrole]
role = ""

[interactions.qol.automod]
sendFlagAttachments = true

[interactions.qol.essaying]
emote = ""
threshold = 1000
ignoredChannels = []

[interactions.qol.minecraftFix]
subRole = ""
minecraftRole = ""

[interactions.qol.pollRestrictions]
allowedRoles = []
disallowedChannels = []
globalMinutesPerChannel = 1
globalMinutesPerUser = 15

[interactions.qol.vedalReplyMention]
vedal = "170187485345742858"
logChannel = ""
ignoredRoles = []
ignoredChannels = []

[[interactions.reactions.bans]]
enables = false
name = "Sample Ban"
match = "samplename|sampleid"
channels = []
ignoredChannels = []

[interactions.swarm]
targetChannel = ""

[interactions.twitch]
authKey = ""
# vedal987: 85498365
pollUser = "85498365"
pollResultsChannel = ""
