token = ""
clientId = ""
guildId = ""

[interactions.utility.info]
logChannel = ""

[interactions.swarm]
targetChannel = ""

[interactions.jp]
targetChannel = ""
translationTargetChannel = ""
deeplAPIKey = ""
