token = ""
clientId = ""
guildId = ""

[interactions.info]
logChannel = ""
saveAttachments = false
# Absolute path
attachmentDir = ""
attachmentBaseURL = ""

[interactions.jp]
targetChannel = ""
translationTargetChannel = ""
deeplAPIKey = ""

[interactions.pendingrole]
role = ""

[interactions.swarm]
targetChannel = ""

[interactions.twitch]
authKey = ""
# vedal987: 85498365
pollUser = "85498365"
pollResultsChannel = ""
